name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allow manual triggering
    inputs:
      environment:
        description: 'Test Environment'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - dev
          - stage

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx cross-env TEST_ENV=${{ github.event.inputs.environment || 'qa' }} npx playwright test
      env:
        # If your tests rely on secrets, map them here from GitHub Secrets
        # CI: true is set automatically by GitHub Actions
        TEST_ENV: ${{ github.event.inputs.environment || 'qa' }}

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

